# Test this Rust package for me
# This github action runs cargo test, cargo fmt, cargo clippy, security audit, cargo miri

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
        - uses: actions/checkout@v2
        - name: Test
          run: cargo test
    
    fmt:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Format
          run: cargo fmt --all -- --check

    clippy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Clippy
          run: cargo clippy --all -- -D warnings

    miri:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Miri
          run: cargo miri test

    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Build
          run: cargo build --release
    